# fly.toml app configuration file generated for nnhjs-blog on 2024-01-01T15:51:04+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nnhjs-blog"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
